spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/part_time?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000ms
